---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-disk
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer  # Immediate is not supported
reclaimPolicy: Delete  # available values: Delete, Retain
