kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-csi-dysk-readonly
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-csi-dysk-readonly
  storageClassName: ""
