version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
      interval: "daily"
  labels:
    - "area/dependency"
    - "release-note-none"
    - "ok-to-test"
  open-pull-requests-limit: 1
