apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-blobfuse
spec:
  containers:
  - name: nginx-flex-blobfuse
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    - name: test2
      mountPath: /data2
    - name: test3
      mountPath: /data3
  volumes:
  - name: test
    flexVolume:
      driver: "azure/blobfuse"
      readOnly: false
      secretRef:
        name: blobfusecreds
      options:
        container: public
        tmppath: /tmp/blobfuse
        mountoptions: "--file-cache-timeout-in-seconds=120"
  - name: test2
    flexVolume:
      driver: "azure/blobfuse"
      readOnly: false
      secretRef:
        name: blobfusecreds
      options:
        container: public
        tmppath: /tmp/blobfuse
        mountoptions: "--file-cache-timeout-in-seconds=120"
  - name: test3
    flexVolume:
      driver: "azure/blobfuse"
      readOnly: false
      secretRef:
        name: blobfusecreds
      options:
        container: public
        tmppath: /tmp/blobfuse
        mountoptions: "--file-cache-timeout-in-seconds=120"
