apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-cifs
spec:
  containers:
  - name: nginx-flex-cifs
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
  volumes:
  - name: test
    flexVolume:
      driver: "foo/cifs"
      secretRef:
        name: cifscreds	
      options:
        source: "//STORAGE-ACCOUNT.file.core.windows.net/SHARE-NAME"
        mountOptions: "vers=3.0,dir_mode=0777,file_mode=0777"
