kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-cifs-flexvol
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-cifs-flexvol
  storageClassName: ""
