---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-smb
spec:
  containers:
    - name: nginx-flex-smb
      image: nginx
      volumeMounts:
        - name: flexvol-mount
          mountPath: /data
  volumes:
    - name: flexvol-mount
      persistentVolumeClaim:
        claimName: pvc-smb-flexvol
