apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-smb
spec:
  containers:
  - name: nginx-flex-smb
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
  volumes:
  - name: test
    flexVolume:
      driver: "microsoft.com/smb"
      secretRef:
        name: smbcreds	
      options:
        source: "//STORAGE-ACCOUNT.file.core.windows.net/SHARE-NAME"
        mountoptions: "vers=3.0,dir_mode=0777,file_mode=0777"
