---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-flexvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "microsoft.com/smb"
    secretRef:
      name: smbcreds
    options:
      source: "//STORAGE-ACCOUNT.file.core.windows.net/SHARE-NAME"
      mountoptions: "vers=3.0,dir_mode=0777,file_mode=0777"  # more options: https://linux.die.net/man/8/mount.cifs
