apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-smb-flexvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/smb"
    secretRef:
      name: smbcreds
    options:
      source: "//STORAGE-ACCOUNT.file.core.windows.net/SHARE-NAME"
      mountOptions: "vers=3.0,dir_mode=0777,file_mode=0777"

