---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-smb-flexvol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-smb-flexvol
  storageClassName: ""
