# Config file for the Skaffold build/dev tool: https://skaffold.dev/
#
# Skaffold is particularly helpful for iterative development
# of the smb-flexvol-installer / helm chart combination.
#
# First set your docker image repo to something you can push to, e.g. one of these:
# - Azure: `skaffold config set default-repo mcr.microsoft.com/MYORG`
# - DockerHub: `skaffold config set default-repo docker.io/MYORG`
# - GCR: `skaffold config set default-repo gcr.io/MYORG`
#
# Changes to the helm chart or docker installer can be deployed using:
# `skaffold run`
#
# Continuous "dev cycle" deploys can be run using:
# `skaffold dev`
---
apiVersion: skaffold/v2beta1
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: smb-flexvolume
      context: deployment/smb-flexvol-installer
deploy:
  helm:
    releases:
      - name: smb-flexvol
        chartPath: helm/smb-flexvol
        values:
          smbFlexVolInstaller.image: smb-flexvolume
        imageStrategy:
          helm: {}
