apiVersion: v1
kind: Namespace
metadata:
  name: flex
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cifs-flexvol-installer
  namespace: flex
  labels:
    k8s-app: cifs
spec:
  selector:
    matchLabels:
      name: cifs
  template:
    metadata:
      labels:
        name: cifs
    spec:
      containers:
      - name: cifs-flexvol-installer
        image: andyzhangx/cifs-flexvol-installer:1.0.0
        imagePullPolicy: Always
        volumeMounts:
        - name: volplugins
          mountPath: /etc/kubernetes/volumeplugins/
        - name: varlog
          mountPath: /var/log/      
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/              
      - name: volplugins
        hostPath:
          path: /etc/kubernetes/volumeplugins/
          type: DirectoryOrCreate
      nodeSelector:
        beta.kubernetes.io/os: linux
