# Set the name of the deployed PersistentVolume[Claim]
nameOverride: "ceres-flights"
fullnameOverride: ""

smbVolume:
  enabled: false
  server: "STORAGE-ACCOUNT.file.core.windows.net"
  share: "SHARE-NAME"
  credsSecretName: # name of k8s secrets to ref
  capacity: 100Gi
  # more mount options: https://linux.die.net/man/8/mount.cifs:
  mountOptions: "vers=3.0,dir_mode=0777,file_mode=0777"  

smbVolumeClaim:
  enabled: false
  request: 10Gi

smbFlexVolInstaller:
  # Install statically linked jq and cifs-utils on each k8s node?
  # Usually required unless running on Azure AKS which already has these
  installDependencies: true
  image: mcr.microsoft.com/k8s/flexvolume/smb-flexvolume
  # Tolerate tained nodes when deploying the DaemonSet?
  tolerations:
  - key: "hub.jupyter.org_dedicated"
    value: "user"
    effect: "NoSchedule"
  nodeSelector:
    hub.jupyter.org/node-purpose: user


  # You MUST configure the path your k8s platform searches for flex volume plugins
  # See https://rook.io/docs/rook/master/flexvolume.html for helpful per-platform tips

  flexVolumePluginPath: /home/kubernetes/flexvolume

  # "Default" location:
  # flexVolumePluginPath: /usr/libexec/kubernetes/kubelet-plugins/volume/exec/

  # Azure AKS:
  # flexVolumePluginPath: /etc/kubernetes/volumeplugins

  # Google GKE:
  # flexVolumePluginPath: /home/kubernetes/flexvolume
