apiVersion: v1
kind: Pod
metadata:
  name: nginx-flex-dysk
spec:
  containers:
  - name: nginx-flex-dysk
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
  volumes:
  - name: test
    flexVolume:
      driver: "azure/dysk"
      readOnly: false
      fsType: ext4
      secretRef:
        name: dyskcreds
      options:
        container: CONTAINER-NAME
        blob: NAME.vhd
