apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-dysk-flexvol
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  flexVolume:
    driver: "azure/dysk"
    secretRef:
      name: dyskcreds
    options:
      container: CONTAINER-NAME
