{{ if .Values.testPod.enabled }}

apiVersion: v1
kind: Pod
metadata:
  name: {{ include "smb-flexvol.fullname" . }}-testpod
  labels:
{{ include "smb-flexvol.labels" . | indent 4 }}
spec:
  nodeSelector:
{{ toYaml .Values.smbFlexVolInstaller.nodeSelector | indent 4 }}
  tolerations:
{{ toYaml .Values.smbFlexVolInstaller.tolerations | indent 4 }}
  containers:
  - name: testpod
    image: debian
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: flexvol-mount
      mountPath: /data
  volumes:
  - name: flexvol-mount
    persistentVolumeClaim:
      claimName: {{ include "smb-flexvol.fullname" . }}

{{ end }}