---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: smb-flexvol-installer
  namespace: kube-system
  labels:
    k8s-app: smb
spec:
  selector:
    matchLabels:
      name: smb
  template:
    metadata:
      labels:
        name: smb
    spec:
      containers:
        - name: smb-flexvol-installer
          image: mcr.microsoft.com/k8s/flexvolume/smb-flexvolume:1.0.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: volplugins
              mountPath: /etc/kubernetes/volumeplugins/
            - name: varlog
              mountPath: /var/log/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/
        - name: volplugins
          hostPath:
            path: /etc/kubernetes/volumeplugins/
            type: DirectoryOrCreate
      nodeSelector:
        beta.kubernetes.io/os: linux
