---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: blobfuse-flexvol-installer
  namespace: kube-system
  labels:
    k8s-app: blobfuse
spec:
  selector:
    matchLabels:
      name: blobfuse
  template:
    metadata:
      labels:
        name: blobfuse
    spec:
      priorityClassName: system-node-critical
      containers:
        - name: blobfuse-flexvol-installer
          image: mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume:1.0.13
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: volplugins
              mountPath: /etc/kubernetes/volumeplugins/
            - name: varlog
              mountPath: /var/log/
      volumes:
        - name: varlog
          hostPath:
            path: /var/log/
        - name: volplugins
          hostPath:
            path: /etc/kubernetes/volumeplugins/
      nodeSelector:
        beta.kubernetes.io/os: linux
