apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: blobfuse-flexvol-installer
  namespace: kube-system
  labels:
    k8s-app: blobfuse
spec:
  selector:
    matchLabels:
      name: blobfuse
  template:
    metadata:
      labels:
        name: blobfuse
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"    
      containers:
      - name: blobfuse-flexvol-installer
        image: andyzhangx/blobfuse-flexvol-installer:1.0.0
        imagePullPolicy: Always
        env:
        - name: KUBELET_VERSION
          value: v1.8
        volumeMounts:
        - name: volplugins
          mountPath: /etc/kubernetes/volumeplugins/
        - name: varlog
          mountPath: /var/log/      
      volumes:
      - name: varlog
        hostPath:
          path: /var/log/              
      - name: volplugins
        hostPath:
          path: /etc/kubernetes/volumeplugins/
      nodeSelector:
        beta.kubernetes.io/os: linux
